# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

DnuSiteBundle:
    resource:  "@DnuSiteBundle/Resources/config/routing.yml"
    prefix:    /
