Dnu\SiteBundle\Entity\Member:
    properties:
        firstName:
            - NotBlank: { message: Il nome è obbligatorio. }
        lastName:
            - NotBlank: { message: Il cognome è obbligatorio. }
        birthCommune:
            - NotBlank: { message: Il Comune è obbligatorio. }
        birthProvince:
            - NotBlank: { message: La Provincia è obbligatoria. }
            - MinLength: 2
            - MaxLength: 2
        birthDate:
            - NotBlank: { message: La data di nascita è obbligatoria. }
            - Type: \DateTime
        residencyCommune:
            - NotBlank: { message: Il Comune è obbligatorio. }
        residencyProvince:
            - NotBlank: { message: La Provincia è obbligatoria. }
            - MinLength: 2
            - MaxLength: 2
        address:
            - NotBlank: { message: L'indirizzo è obbligatorio. }
        civNum:
            - NotBlank: { message: Il numero civico è obbligatorio. }
        telephone:
            - NotBlank: { message: Il telefono è obbligatorio. }
        email:
            - Email: { message: Inserire un indirizzo e-mail valido. }
        privacyAcceptance:
            - Type: boolean
            - "True": { message: L'accettazione della privacy è necessaria per proseguire. }
        termsAcceptance:
            - Type: boolean
            - "True": { message: L'accettazione delle condizioni è necessaria per proseguire. }
        newsletterAcceptance:
            - Type: boolean
