parameters:
#    dnu_site.example.class: Dnu\SiteBundle\Example

services:
#    dnu_site.example:
#        class: %dnu_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
